<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * @file
 * Contains az_nav.module.
 */

/**
 * Implements hook_theme().
 *
 * @param $variables
 */
function az_nav_theme(&$variables) {
  return [
    // Display atom select list items and their sublists.
    'user_popup_menu' => [
      'variables' => [
        'uid' => 0,
      ],
    ],
  ];

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function az_nav_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /*if ($form['#form_id'] == 'entity_embed_dialog') {
      $form['shitty'] = [
        '#type' => 'container',
        'checkbox' => [
          '#type' => 'checkbox',
          '#title' => t('hey james dude'),
          '#default_value' => false,
        ],
      ];
    } */
  return;
}

/**
 * Implements hook_preprocess_page().
 *
 * @param $variables
 */
/*
function az_nav_preprocess_page(&$variables) {
  $active = \Drupal::service('domain.negotiator')->getActiveDomain();

  $variables['active_domain'] = str_replace('_', '-', $active->id());
  return;
}
*/

/**
 * Implements hook_preprocess_html().
 *
 * @param $variables
 */
function az_nav_preprocess_html(&$variables) {
//$active = \Drupal::service('domain.negotiator')->getActiveDomain();

//$variables['active_domain'] = str_replace('_', '-', $active->id());
  return;
}


