<?php

/**
 * @file
 * Contains az_theories.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function az_theories_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the atomizer module.
    case 'help.page.az_theories':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Implement the Theories Taxonomy');
      return $output;

    default:
  }
}

function az_theories_preprocess_taxonomy_term(array &$var) {
  return;
}


